// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASdD3neFmJ5DQ_ZzPuEomV9dJkB0hqoiw',
    appId: '1:1043744164920:web:d08f2961fe2913a3bd2acd',
    messagingSenderId: '1043744164920',
    projectId: 'my-note-542',
    authDomain: 'my-note-542.firebaseapp.com',
    storageBucket: 'my-note-542.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlCjWdc2kLYaP4Yt1wv8BQl__JJGaUT0',
    appId: '1:1043744164920:android:71b8f62a2dba436cbd2acd',
    messagingSenderId: '1043744164920',
    projectId: 'my-note-542',
    storageBucket: 'my-note-542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvnHHB4iRYEdTrZLoUPwJSNiJVqPhTnc',
    appId: '1:1043744164920:ios:b81ed95dacaa454abd2acd',
    messagingSenderId: '1043744164920',
    projectId: 'my-note-542',
    storageBucket: 'my-note-542.appspot.com',
    iosBundleId: 'com.noteapp.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACvnHHB4iRYEdTrZLoUPwJSNiJVqPhTnc',
    appId: '1:1043744164920:ios:88d7496ee0e86fe1bd2acd',
    messagingSenderId: '1043744164920',
    projectId: 'my-note-542',
    storageBucket: 'my-note-542.appspot.com',
    iosBundleId: 'com.noteapp.noteApp.RunnerTests',
  );
}
